### ISSUE TITLE
Check inventory coverage options

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#376]
No text appears when there are segments that aren't covered in the feature system.

**Comment by bhallen** [comment]
@kchall Could you describe how you ran into this issue? When loading a corpus with segments that aren't in the specified transcription/feature system, the user is given the option to specify it with all default values, and otherwise the segment is left outside the feature system. But in the latter case, "Check corpus inventory coverage" still seems to successfully detect the un-featured segment(s).

Or could it be that you clicked the "Check corpus inventory coverage" button when no feature system had been specified? I just added a warning box to handle this case.

**Comment by kchall** [comment]
Sorry, I think this is one that Michael and I talked about, so I didn't explain it clearly enough here. You're right that PCT does detect un-featured segments; what I was trying to say is that there is not text surrounding it to say that there is a problem with those segments. In most cases, it's pretty obvious. But the issue came up in a corpus where somehow a space was being treated as a character (presumably it was between two delimiters?), and wasn't covered in the feature system. So, the box popped up but seemed to be empty because it only listed an invisible character. So it would be useful to have some text that at least said "The following characters are not covered:" (and maybe even had a special note about invisible ones?). Unfortunately I don't remember which corpus this was right now.

**Comment by mmcauliffe** [comment]
Just a note to say that spaces should never get parsed into a transcription (i.e., they're always ignored).  I'll add some checks to make sure that doesn't happen.

**Comment by bhallen** [comment]
Maybe it wasn't a space, then, but an empty string? (I imagine there could have been two segment delimiters next to each other.)

**Comment by bhallen** [comment]
fixed in develop: added text to clarify the warning message
