### ISSUE TITLE
What features are needed in order for an organized inventory to be created?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#380]
I've been working on creating feature files for a variety of other corpora (Buckeye, Korean, CSJ, Cantonese), but I can't quite figure out what features PCT needs in order to create an IPA-chart style organized inventory. In particular:

-is PCT case-sensitive when it comes to features? e.g., will [LABIAL] be treated the same as [labial]?

-what feature is needed to recognize stops? e.g., I have [p], [t], [k], etc., coded as [-continuant] in the Buckeye corpus, but they're not showing up in my inventory as stops -- they're just listed in the "other" category at the bottom. 

-similarly, how about affricates? In the Buckeye, they're currently [-continuant], [+delayed release], and similarly just showing up in the "other" category.

More generally, it would be good to have a description of what features are needed to properly interpret the inventory visually, so that we can include this in the documentation.

**Comment by mmcauliffe** [comment]
Yes, it is a super big mess at the moment!  It's hardcoded to either the SPE style or the Hayes style, neither of which is meant for a computer, and both assume the reader has knowledge of what is what.  So it needs overhauling, which is what I was doing on the better-categories branch, but it's still a work in progress.

To answer your questions:

1.  Yes, it is case-sensitive at the moment, it'd be nice to have it not be.

2. For Hayes-style features, stops are: -sonorant, -continuant, -nasal and -delayed_release.  I'm thinking that it might be that your delayed release feature has a space instead of an underscore?

3. Affricates are -sonorant, -continuant, +delayed_release (probably being affected by the lack of underscore)

More generally, we should allow the user to specify which feature combinations will select which class in a hierarchical fashion.  So you can select features that specify consonant vs vowel, and then within consonant, select features that specify place of articulation, manner, etc.

**Comment by kchall** [comment]
Ah, I see...yep, I had downloaded a corrected version of Hayes' feature chart, and he used capital letters for major place features, and no underscore. Seems to be working now. But yeah...we definitely need to figure out a way to make it more viable!

**Comment by kchall** [comment]
@jsmackie as well

**Comment by mmcauliffe** [comment]
@kchall Ok, so I added a button in the Edit feature system dialog (under "Display"). Once it gets clicked, brings up a dialog with 5 tabs, one for what I've termed "major" distinctions (vowels vs consonants, voiced vs unvoiced, round vs unround and diphthong), and then a tab for places of articulation, manners of articulation, vowel height and vowel backness.  It uses the feature completion widget that the segment select uses, but instead of highlighting segments in the feature matrix (since the IPA one has so many), it puts included segments into a tooltip.  Longer term solution that's more intuitive is still needed, but this should be functional and relatively straightforward for the 1.1 release.
Additionally, all features should be completely case insensitive now (they should all get converted to lower case and any look ups will use lower case).  Differences in underscores and hyphens are maybe out of the scope, though we could do some standardizing of those.

Let me know what issues you run into with it!
