### ISSUE TITLE
Acoustic similarity on large folders

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#401]
Figure out what's going on with acoustic similarity calculations using directories that have >100 sound files per folder. The calculations seem excessively slow.

**Comment by mmcauliffe** [comment]
So it looks like it is indeed related to a sound file that is too short, rather than folders that are too long.  In that particular folder, there was a file name "Korean_female_Korean_305_s_before_o_after_m_19.wav" which was 0.021 seconds long, which is below the window size of 0.025, and removing that file allowed the calculation to go smoothly.  There are a couple of options:

1.  Ignore all files shorter than that
2.  Throw an error message and stop the calculation
3.  Allow users to specify the window size
4.  Allow for greater interactivity, such as checking durations of sound files when directories are specified

Probably the best for the moment would be 2, so I'll work on implementing that one.  Allowing users to specify the window size I think is probably the worst, since it has consequences that most users would not be aware of (decreased frequency resolution).

**Comment by mmcauliffe** [comment]
This is addressed in the latest versions of python-acoustic-similarity, so I'll close it here.
