### ISSUE TITLE
weird digraph issues

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#413]
1. Just a comment for ourselves: we should indicate in the help files about digraphs that users should make sure to list the longest digraphs first (e.g., [ts'] before [ts]); otherwise, PCT won't parse them correctly.

2. Related to the above, I would have expected PCT to parse a form like [ts'idga] as *[ts.'.i.d.g.a] if the digraphs weren't entered in the right order. But instead, it seems to delete the apostrophe and return *[ts.i.d.g.a] instead. Why?

3. If parentheses are included in digraph sequences, the following error is returned:
Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 89, in run
    corpus = load_transcription_corpus(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/text_transcription.py", line 114, in load_transcription_corpus
    spell = ''.join(trans)
TypeError: sequence item 0: expected str instance, tuple found

**Comment by mmcauliffe** [comment]
Once io-standardize gets merged in, this should be all fixed.  It should also make it so that longer digraphs are matched before smaller ones.  The reason why the apostrophe disappeared was because the fallback for the digraphs was '\w' (any alphanumeric character or underscore).  I changed it so that it's '\S' (any non-whitespace character) so punctuation will show up in transcriptions if digraphs are specified.
