### ISSUE TITLE
Editing digraphs

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#419]
(AO): "It would be really useful to be able to change the digraphs (or especially to add ones you've forgotten) without having to remake the corpus from the beginning."

**Comment by bhallen** [comment]
The corpus object currently doesn't store the original input text, right? I think that we'd need to have it do so if we wanted to let the user modify the assignment of input file substrings to segments after the corpus is loaded. But for large corpora, this would mean that the corpus object in memory is much larger, right?

Unless someone has another idea for addressing this enhancement, I'm leaning toward making this a 'wontfix'...

**Comment by kchall** [comment]
Yeah, I don't think there's likely to be a way to do this that is really any easier than just having the user re-do it. But maybe we could make re-doing it easier FOR the user? e.g., by saving the original set of digraphs they used and allowing them to export it as a .txt file so that they can edit, copy, and paste the next time around?

**Comment by bhallen** [comment]
That sounds like a good idea to me. Right now the digraph input just produces a string containing all the digraphs (e.g. 'sh, ph, tl'). But where do we put the actual "download digraph list" button? Putting it right next to the "construct a digraph" button in corpus read-in seems a little premature, since the user won't know if they've missed some digraphs (and therefore need to save the list to modify later) or not. And adding it as a menu option accessible after the user has read in the corpus means that they might not be able to find it, or even know it exists. Maybe we should do both?

Also, by calling these things "digraphs", users might think that they can't add "trigraphs"/"quadrigraphs"/etc. Unfortunately, the word "polygraph" already means something else. :) Should we change the word "digraph" to something like "digraphs and other multi-character segments" (admittedly long and clunky)?

**Comment by mmcauliffe** [comment]
So I've updated the interface to call them "Multicharacter segments" instead of digraphs.  In terms of addressing this issue, I wonder if doing a preliminary analysis of bigram/trigrams frequency (relative to the unigram frequencies) would allow us to suggest likely digraphs to the user, which would help alleviate some of the need for redoing them if the corpus has a lot of multicharacter segments.

**Comment by kchall** [comment]
Well, doing some pre-processing might be nice, but I think that should be a lower priority right now. As for when / where the list could be downloaded, I think just putting it in the same menu with "Export corpus" and  "Export features" should be fine.

**Comment by mmcauliffe** [comment]
@kchall So PCT now creates a log file named 'pct_gui.log' in the log directory of PCT's storage (by default that's set to ~/Documents/PCT/CorpusTools).  Whenever a corpus is imported, it adds lines to that file (though it gets overwritten each time the PCT gui starts up, to keep the file size small) for each annotation type specified in the import dialog.  It outputs all the parsing settings, so digraphs, delimiters, ignored punctuation and number behavior.  So that would be where the user would find the digraphs if they wanted to reimport the corpus with new ones.

**Comment by kchall** [comment]
Hmm, this sounds great. But the log file I got when importing the Lezgian corpus (with lots of digraphs, ignored punctuation, etc.) only contained the following:

INFO:root:Importing transcription corpus
INFO:root:Annotation type info
INFO:root:--------------------
INFO:root:

(and no other information....)

**Comment by kchall** [comment]
Sorry, there was an error message in Python, too:

--- Logging error ---
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u02b7' in position 75: ordinal not in range(128)
Call stack:
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 80, in run
    log_annotation_types(self.kwargs['annotation_types'])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/helper.py", line 343, in log_annotation_types
    logging.info(a.pretty_print())
Message: "transcription:\n    Ignored characters: (, !, ), '\n    Digraphs: tʷ', tʷʰ, tʷH, tʷ, sʷ, zʷ, qʷH, kʷH, kH, tH, pH, qH, tsʰ, tsH, tʃH, gʷ, kʷʰ, tsʷʰ, tsʷH, tsʷ', tsʷ, ts', ts, t', kʷ', k', p', tʃʰ, tʃ', tʃ, qʷʰ, qʷ', q', qʷ, kʷ, pʰ, tʰ, kʰ, qʰ, ʁʷ, χʷ\n    Transcription delimiter: ,\n    Morpheme delimiters: -\n    Number behavior: None\n"
Arguments: ()

**Comment by mmcauliffe** [comment]
Should be fixed now, let me know if it isn't.

**Comment by kchall** [comment]
So, it does work with other corpora as far as I can tell. Could we add in information about the name of the source file used and the name of the corpus, too? Thanks!

**Comment by kchall** [comment]
But, no, it still gives me the same error for the Lezgian corpus.

**Comment by mmcauliffe** [comment]
Oh sorry, that's because GitHub was dumb and didn't sync my changes when I told it to.

**Comment by mmcauliffe** [comment]
This should actually work now, it seems like the logging API changed in Python 3.3, so I had done it the old.
