### ISSUE TITLE
Issue with pronunc. variants / Minimal Pair counts?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#426]
In running the functional load of t/d and th/dh in the Buckeye corpus, using minimal pair counts, I get exactly the same results if I select "Count each word token as a separate entry" or if I select "Weight each word type by the relative frequency of its variants."

Shouldn't the results for the weighted types be smaller? It looks as though it's not actually *weighting* the types but rather just still counting each token as a single separate type.

@mdfry @mmcauliffe

**Comment by mmcauliffe** [comment]
That would be because the minimal pair algorithm only uses type frequency, so the two have the same number of types, thus the same minimal pairs.  We could recode it so that minimal pairs uses frequency information, or disable some pronunciation variants options for minimal pairs.

**Comment by kchall** [comment]
Hmm, ok, that's not what I was expecting. The point of *weighting* the types by the token frequency of each variant is specifically to get that information into the regular use of types. So ideally, we'd re-code, but if we need to just disable it for now, that's ok, too. But let's not have it actually returning this result.

**Comment by mmcauliffe** [comment]
Alright, functional load now works with frequency values, so all the options should give somewhat different values (some do overlap).  Relative counts remove the frequency elements (so it's divided by the frequency of all the neutralized elements, rather than the cardinality of them).  Using raw counts is easier to see the differences.

I also enabled type and token frequency for weighted and separate tokens, since they have different behaviors.  For Weight, type frequency weights it by the number of variants for a word, and token frequency weights it by the frequency of the word over all.  For separate tokens, type frequency assigns each variant a frequency of 1 and token frequency assigns it the frequency that the variant occurred.
