### ISSUE TITLE
sets of segments

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#440]
Cool, this looks promising! I'm just at the airport trying to quickly try it out with the example corpus -- trying to do ProD of +/-back vowels in the example corpus. I can set up the feature and the filter, but no segments actually show up in the selection box. No error is thrown, and a results table is given, but it's also blank. That is, it looks as though PCT is working, but with no visible reporting of the segments being analyzed?

**Comment by mmcauliffe** [comment]
Yes, so that's probably because no vowels are defined only by back, I would think, since it's a 5 vowel system (i/u and e/o differ in back and round, and a doesn't have a -back pair).  I don't know how to do covarying features at this point, but if you try out voice, it'll give you some idea of the current functionality.

**Comment by mmcauliffe** [comment]
Ok, so it's slightly better now.  Now if you type in all the features that covary, it'll discover the pairs you mean.  So for doing +/- back vowels in the example corpus, assuming Hayes, you'll have to type "back, front, round, labial" and assuming spe, "back, round".  So it's obviously not great that you have to type in all four of those somewhat redundant features, but I don't quite see a way around it without detecting that alpha-round is alpha-labial.

One remaining big issue that should be relatively straight forward is getting more than two sets of segments this way.  For larger systems, if you type in "back, front, round, labial" it'll give you just the first two sets that covary, when ideally it should give you all of them, and then let you narrow it down as you wish, and if you hit add with more than 2, it should do the combinations code as in segment pairs.

**Comment by kchall** [comment]
Hmm, ok...a bit clunky, but should be ok for now. Thanks!

**Comment by mmcauliffe** [comment]
Ok, added some improvements so that it detects redundant features and ignores those.  So in your example, entering "back" or "round" (or both) along with "-low" in the filter field will show the desired pairs.

I also added support for multiple sets (more than 2).  Let me know if it's feeling better!  It's still kinda unresponsive for large inventories, since entering one feature doesn't do anything.  Maybe at some point we can add suggested features or something to increase responsiveness.
