### ISSUE TITLE
Error in selecting feature pair?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#451]
In trying to calculate ProD on voiced / voiceless pairs in Gitksan (using the "Add feature pair" option instead of manually selecting segments), I get the following error:

KeyError: 'voice'
Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1698, in updateSegments
    feature_values = self.inventory.find_min_feature_pairs(features, others)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 1714, in find_min_feature_pairs
    if any(seg[f] not in set('+-') for f in features):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 1714, in <genexpr>
    if any(seg[f] not in set('+-') for f in features):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 109, in __getitem__
    return self.features[key.lower()]

**Comment by kchall** [comment]
@bhallen add error message to indicate that all segments must be specified for features

**Comment by mmcauliffe** [comment]
Ok, I fixed it so that it'll catch that exception and ignore unspecified segments.  The error message stuff should probably be warnings attached to the initial association of feature systems to corpora (like "This feature matrix does not fully specify all segments in the corpus.  Are you sure you want to use this feature system?").

**Comment by bhallen** [comment]
Hm, I don't see that your commit d27ec2a affected the behavior of this bug... but my commit 0e98995 at least added an Error pop-up that prevents users from using the "Add feature pair" option when segments aren't all specified.

Should we consider this closed for now?

**Comment by mmcauliffe** [comment]
Ok, I added a warning message on associating feature systems to corpora, so I definitely don't think we need every segment specified for feature pairs, especially if the unspecified segment is irrelevant to the feature being selected, i.e., it doesn't matter that /k/ isn't specified when you're looking at rounding in vowels.

**Comment by bhallen** [comment]
I thought the big problem with this bug is that users are prevented from adding /any/ feature pairs if at least one segment is unspecified for features? At least that's what happens on my end. So it seems like it might be better to prevent users from getting into this situation than to let then wonder why their search for +anterior segments failed even though all the +anterior segments are fully specified, no?

**Comment by mmcauliffe** [comment]
Ah, yes, there were a couple other cases where KeyErrors were getting thrown.  I've fixed those up.  So now they can add "anterior" and see the pairs that are defined with anterior even if there are some segments that aren't specified.  There's still a slight issue that if they're expecting an anterior segment to show up, but it isn't specified, then it won't be processed by this, but at least it won't fail outright.

I commented out the critical error message, but we can re enable it if that's a more desirable solution.  Requiring that all segments be specified to do any sort of featural analysis seems to me like it would place a bit of a high burden on users that might not care if everything is specified.

**Comment by bhallen** [comment]
This all sounds like a reasonable resolution to me. I'll leave this issue open but re-assign it to the 1.2 milestone so that we'll remember to discuss it at our next meeting.

**Comment by kchall** [comment]
this seems better to me!

**Comment by kchall** [comment]
I think this is fixed but see issue #484 as well.
