### ISSUE TITLE
bug with example corpus?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#457]
So, I got someone with Mac OS 10.8 to try the executable version of PCT v. 1.1.1, and that seems to work. But, when she downloaded the example corpus to test things out, PCT claimed there were no transcriptions associated with the corpus and therefore no analyses could be done. The feature system itself is fine -- you can get a summary of the inventory -- and the transcriptions show up in a correctly named "transcription" column.

**Comment by bhallen** [comment]
It sounds like this is the same as #453. The problem was that the file had no segment delimiters, and I didn't know to manually set the transcription column to the "transcription" AnnotationType.

It seems that for whatever reason, the transcription column in the public example.corpus has the same problem.

I just replaced the public example.corpus with a fixed version, and the public example.txt with one that has segment delimiters. Downloading example.corpus and looking at its features now works, so this issue is resolved.
