### ISSUE TITLE
BUG in sample corpora and also in feature systems

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#460]
This issue has come up twice today for people who have recently downloaded the most recent version of PCT and tried to download the sample corpora -- PCT seems to be looking for our local copy of the corpora:

Traceback (most recent call last):
File "/Users/speechincontext/Documents/Michael/CorpusTools/corpustools/gui/iogui.py", line 62, in run
File "/Users/speechincontext/Documents/Michael/CorpusTools/corpustools/corpus/io/binary.py", line 105, in load_binary
_pickle.UnpicklingError: invalid load key, '<‘.

Relatedly, one of the people tried to create their own corpus and had a similar issue when creating a new feature system:

Traceback (most recent call last):
File "/Users/speechincontext/Documents/Michael/CorpusTools/corpustools/gui/iogui.py", line 105, in run
File "/Users/speechincontext/Documents/Michael/CorpusTools/corpustools/corpus/io/textgrid.py", line 280, in load_discourse_textgrid
NameError: name 'load_binary' is not defined

This user also asks: 

I’m running on a 2014 MacBook Air with Yosemite, if that helps (by the way, will it work still when El Capitan is released in a few weeks?).

**Comment by mmcauliffe** [comment]
So the unpickling error for sample corpora should be fixed.  I don't know the exact cause, but Dropbox for some reason was returning a 404 not found for the corpora, so the .corpus file was actually an html file, which is why it threw an error when it hit '<' for the '<html>' tag.  I rejoined the public folder and double checked the links of the corpora, and they were the same, and rerunning the download works now.  So my thinking is that Dropbox expired those links either due to unuse (maybe no one was joined to the shared folder?) or it periodically does it?

As for the other issue, can you verify that they're running 1.1.1, looking at the code of it, that should be fixed (it was an issue in 1.1.0, but it should definitely be fixed for 1.1.1).

As for future compatibility, I think it should be okay with whatever new versions, usually Apple's pretty good about being compatible with apps compiled for previous versions.  Apps compiled on later version generally do not work on previous versions, however, so that's why we do 10.8 build machines, since 10.9 introduced some backwards incompatible changes to some system libraries.

On a related note, the PCT installer works on Windows 10, and PCT looks good even with a 4K display, so I'm happy about that.

**Comment by kchall** [comment]
Thanks, Michael! They have confirmed the ability to download the sample corpora, and that they had mistakenly gotten 1.1.0 -- so everything should be ok now.
