### ISSUE TITLE
Command Line Functional Load Issues

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#476]
1. In the help file, Example 2 for running FL on the command line is as follows; it's supposed to be a case where the average FL across all pairs with [m] is calculated:

pct_funcload example.corpus -p m -a deltah -t type -o output.txt

Currently on the master branch, this results in an error, presumably because there is no argument for setting it to be relative FL instead of pairs (-e) in the command line given. This should be fixed in the documentation.

2. If deltah is specified as the algorithm, an error occurs, presumably related to the lack of setting environments. Can we add the environment specification to the deltah algorithm? 

3. The actual environment specification is still unclear to me. The information for format says: "positions separated by commas, groups by slashes, e.g. m/n,i matches mi or ni."
But if for instance I do a search in the example corpus as follows, trying to find minimal pairs before [a]:
pct_funcload example.corpus -p pairs.txt -t type -w a
...with [m] and [n] in the pairs.txt file, I get a return of 0, even though there is the minimal pair [mata] / [nata]. Am I misinterpreting how the algorithm is interpreting the environments? (I similarly get results of 0 if I specify the right-hand side to be ata, but it correctly gives me this minimal pair if I just don't specify any environments.)

4. How are word boundaries specified in the environment selection?

**Comment by bhallen** [comment]
1. Is there a particular reason why you didn't include the -e flag?

1. I'm working on adding environment filters to the deltah functions right now. It should be finished by the end of the week at latest.

2. The problem there isn't one of the environments, just one of the segments themselves. Specifically, (in a decision I've regretted since) the transcriptions in example.corpus have no [a] in them, only [ɑ]. When you run the call you wrote out with -w ɑ instead of -w a, it successfully finds the deltah.

3. To put the # symbol in an environment, you need to escape the hash mark by typing \# . This is also something I'll put in the documentation.

**Comment by kchall** [comment]
Thanks, Blake!

1. The -e flag is missing in the documentation -- i.e., this is the verbatim command listed for this operation, but it's missing the key part. 

2. Great!

3. & 4. Ah, got it -- will double-check that it's working.

**Comment by bhallen** [comment]
Thanks for the clarification. I fixed the typo in the documentation.

Calculating deltah FL should now work without problems, and I've also fixed a bug in relative FL calculations. Optimistically, I'll close this issue now, but please let me know if you hit any other snags using the command line scripts.
