### ISSUE TITLE
Read the Docs -- Builds failing?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#483]
Builds have failed for the past 3 months. Is this something we can fix or is it something they need to fix on their end?

**Comment by mmcauliffe** [comment]
I think I fixed it, there was something checked that shouldn't have been checked.  Documentation is now only failing for v1.0.0 and 1.0.1, but I think that's okay since they're outdated.

**Comment by kchall** [comment]
@mmcauliffe Hmm, can you tell us how you fixed this last time? Builds are all failing on the develop branch and have been for the past five months...

**Comment by mmcauliffe** [comment]
Yes, I can see how my previous description would leave something to be desired...

But this is actually a different issue!  Before it was trying to install PCT on the readthedocs server which was causing some issues from dependencies that couldn't be installed.  But installation is not required to build the documentation, so that's what I unchecked.

This time it looks like just the pdfs are failing to build, but the html is fine.  I've updated it to not build pdfs (I don't know how much their used and it's a bit finicky compiling them from rst.  If you want to track down the issue, there's error logs on RTD, I think Blake has access, but I can give other people access as well.  But in the meantime, the badge should be green again, and the html has been building fine this whole time.

**Comment by kchall** [comment]
Super, thanks, Michael. It would be nice to have the .pdfs working as well, but I can live without them. 

I agree that the html is now working, but I'm slightly confused when you say it's been building fine the whole time -- both because my updates weren't showing up and because it looks like they were failing: http://readthedocs.org/projects/corpustools/builds/ 

It doesn't really matter, since they are definitely working now...just wondering. ;-)
