### ISSUE TITLE
importing corpus (GUI): no trans delimiter

### ISSUE THREAD

**Issue by bhallen** [PhonologicalCorpusTools/CorpusTools#485]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/corpustools-1.1.0-py3.4.egg/corpustools/gui/iogui.py", line 107, in run
    corpus = load_corpus_csv(**self.kwargs)
TypeError: load_corpus_csv() missing 1 required positional argument: 'trans_delimiter'

**Comment by mmcauliffe** [comment]
It looks like in commit 2300ad4918ca0e43da34a8f382fe17a540ce6f40 you added `trans_delimiter` as an argument to load_corpus_csv.  In the initial versions of `load_corpus_csv`, it did take a `trans_delimiter` argument, but since transcription delimiters are properties of transcription columns rather than files, the detection and specification of transcription delimiters got moved to annotation_types.  The rationale being that different transcription columns could feasibly have different delimiters and csv files could presumably not have transcription columns.  In one case, a file-wide transcription delimiter causes an error and in the other the `trans_delimiter` argument/keyword argument is unused.

I guess in that change, I didn't update the command line scripts, since they don't have any unit tests, so I didn't realize there was a problem with them.  Whoops!

**Comment by bhallen** [comment]
Is your suggestion, then, to remove that argument and leave trans_delimiter detection up to inspect_csv? It would also be fine instead to just make trans_delimiter a kwarg for load_corpus_csv, right? This would give CL users more control.

Relatedly, it seems that importing a corpus in the GUI still wouldn't work: if annotation_types isn't None, then best_delimiter never gets assigned a value by inspect_csv, leading to a problem when it tries to split out the headers. What was the intended behavior here?

**Comment by mmcauliffe** [comment]
So my thought with the column delimiter is that it's sort of required to specified for importing a csv, so that's why it's the argument `delimiter`.  We could have it as a keyword argument set to None by default, in which case we do `inspect_csv` to see what the most likely column delimiter is (from the limited set that PCT considers).

**Comment by bhallen** [comment]
resolved by 7d50600c132dc607504502468314e7ebefaa0225
