### ISSUE TITLE
"Windows" menu

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#495]
In the "Windows" menu, add an option to go back to the main corpus window (at least for Macs); also add an option to close all windows except the main corpus window?

**Comment by jsmackie** [comment]
I added the option to close all the results windows currently open. I also added an option to go to the main window, but I can't test it on Windows, because as soon as I click on the "Window" menu it brings the main window to the front anyway. I'll leave this open until a Mac user can confirm this for me.
