### ISSUE TITLE
Travis CI errors

### ISSUE THREAD

**Issue by bhallen** [PhonologicalCorpusTools/CorpusTools#538]
@mmcauliffe 

Travis CI is working normally for Python 3.4 on develop, but it is erroring for Python 3.3 on develop, as well as for both version of Python on master. The erroring runs give vague error messages like:

`The command "bash continuous-integration/travis/install.sh" failed and exited with 1 during .`

We're thinking about having a mini-retreat to get all of our unit tests under control soon, so it would be great if Travis CI were working properly for us. Could you advise on how to stop it from erroring?

**Comment by mmcauliffe** [comment]
From looking at the past few builds on develop, it doesn't look like it's erroring out too much.  The only one I saw during the install script was a 500, which is probably just a transient connection error.  Is there a particular build that I should see for it?  The master errors should be fine once it gets updated from develop.  In general, you/I might want to switch the python versions being built against (since 3.3 is pretty old, and 3.5 is the latest stable).  I could update it in the near future to be in line with my current travis configs from other projects if that'd be helpful.

**Comment by bhallen** [comment]
Huh, oh yeah, fortunately the builds I triggered when I posted this issue worked fine. (Well, failed instead of errored.) I guess before that, it looked like there was something more nefarious going on, like some misconfiguration causing the 500 errors. Thanks for calling my accidental bluff!

I agree it's probably best to replace our Python 3.3 build with a 3.5. I think I should just be able to edit travis.yml accordingly, but if you do have other stuff in your new configs that you think would be helpful, by all means add it in.
