### ISSUE TITLE
Buckeye Corpus -- REPORT FROM USER

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#539]
@mmcauliffe 

From a user:

 In trying to upload the Buckeye Corpus I got the following error message, which the program asked me to forward to the developers. 

Could you point me in the right direction for resolving the issue and moving forward?

Traceback (most recent call last):
File \"C:\Users\SpeechInContext\Documents\GitHub\CorpusTools\corpustools\gui\iogui.py\", line 111, in run
File \"C:\Users\SpeechInContext\Documents\GitHub\CorpusTools\corpustools\corpus\io\multiple_files.py\", line 206, in load_directory_multiple_files
File \"C:\Users\SpeechInContext\Documents\GitHub\CorpusTools\corpustools\corpus\io\multiple_files.py\", line 251, in load_discourse_multiple_files
File \"C:\Users\SpeechInContext\Documents\GitHub\CorpusTools\corpustools\corpus\io\multiple_files.py\", line 60, in multiple_files_to_data
File \"C:\Users\SpeechInContext\Documents\GitHub\CorpusTools\corpustools\corpus\io\multiple_files.py\", line 286, in read_phones
ValueError: could not convert string to float: \'60.191694 122\'

**Comment by jsmackie** [comment]
It looks to me like it's a parsing or delimiter error. The code is trying to make a float out of a string. The string does contain a float (60.191694), but it also has a space and an integer (122). Those numbers probably should have been separated by one of the numerous .split() calls in that function, and maybe there's a comma or something missing between them?

**Comment by mmcauliffe** [comment]
Right, so the general format for buckeye phone files is "timestamp 122 phone", so it tries to extract the time stamp and the phone.  The annoying thing with the Buckeye corpus that I haven't gotten around to writing Mark Pitt about is that some phone labels have been transposed to to the following line, so something like:

timestamp1 122
timestamp2 122 phone1 phone2

where it should be:

timestamp1 122 phone1
timestamp2 122 phone2

For this reason (and other errors in the data), other buckeye parsing packages (i.e. https://github.com/scjs/buckeye) just don't parse some files.  The version we've been using internally was fixed up by me several years ago and I just haven't gotten around to sending those files to Mark.  I'll try to do that this month, since I think it'd be useful to have a fully functioning/consistent Buckeye corpus available to the public.

In the meantime, there are a couple of workarounds that could be implemented.  Probably the best and easiest would be to just skip discourses that have these kinds of errors.  That would involve wrapping https://github.com/PhonologicalCorpusTools/CorpusTools/blob/c8f629e5fbcc4e4b6f5775d94213ad6f1e9c12b0/corpustools/corpus/io/multiple_files.py#L203 to https://github.com/PhonologicalCorpusTools/CorpusTools/blob/c8f629e5fbcc4e4b6f5775d94213ad6f1e9c12b0/corpustools/corpus/io/multiple_files.py#L207 in a try-except block.  I recall some other errors that affect the consistency of the overall data (as this does as well, since it needs to find the exact phones that are listed in a word's surface transcription).

Sorry about all this, should have taken care of it years ago...

**Comment by kchall** [comment]
Great, thanks. Michael F. will implement the workaround for the next release (including a warning that that is happening), but it would be great if you (Dr. Michael) could communicate with Mark about getting a fixed version of the corpus available.

**Comment by kchall** [comment]
@mdfry  -- Any chance you'd still be interested in tackling this?

**Comment by kchall** [comment]
@mdfry -- OK, trying this with a freshly downloaded copy of the Buckeye corpus. PCT can load the corpus, BUT it only seems to be reading in some subset of the files to build the corpus from. E.g., it seems to have only created the corpus from the files labelled s2303b, whereas it should have found all of the files not only for subject 23, but also for the other subjects 01-40. I'll send you a link to the folder I'm using. Not sure whether this was a lurking problem or one that is new given the tweaks you made. (NB: I'm not actually sure whether PCT is expecting a folder with all of the "lowest" level Buckeye files all together, or whether it can handle parsing a folder with sub-directories. I tried it both ways, though, and had basically the same issue both times.)

**Comment by mdfry** [comment]
I had taking the items in a loop out of the loop when I added the try statement, as such it only 'tried' on the last item in the loop. Should be resolved now (with misformatted files skipped over)
