### ISSUE TITLE
Add tests for Environment Filters in functional load

### ISSUE THREAD

**Issue by jsmackie** [PhonologicalCorpusTools/CorpusTools#544]

**Comment by kchall** [comment]
Note: the environment selection window here also needs to be edited somewhat. Specifically, it should be analogous to the one used in ProD, where the user can't specify the "target" segments, because they're identical to the segments or pairs that are selected for the FL calculation itself. (This is different from the environment selection in, say, phonological search, where the target can be specified.) @jsmackie

**Comment by jsmackie** [comment]
This turned out to be a super easy fix, and it was just a matter of changing a single parameter.
