### ISSUE TITLE
missing options?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#578]
There are two options we used to have that no longer seem to be there. I've taken them out of the documentation, but I just wanted to double-check that they were removed on purpose:

1. "PCT will also issue certain warnings if various parameters aren’t met.
It is possible to turn warning messages off by going to “Options” /
“Show warnings.”"

2. "To manually see whether there is a more recent version of PCT available
for download, click on "Help" / "Check for updates..."."

**Comment by jsmackie** [comment]
The generic "warnings" was removed because it has been overtaken by specific warnings in the Reminders tab of the Preferences menu (ask before saving corpus, ask before saving feature file). The option to "check for updates" isn't available if you're running pct_debug. It should only appear in the executable version.
