### ISSUE TITLE
order in main corpus window?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#583]
The order of columns in the main corpus window seems to have changed recently, from Spelling - Transcription - Frequency to Transcription - Spelling - Frequency. It doesn't too much matter, I guess, though it's slightly disconcerting; the main place where it seems to make a difference, though, is when using the small search box at the top of the main corpus window. That box seems to search the LEFTMOST column, regardless of what information that contains; so, it used to be searching spelled words and now seems to be searching transcriptions. I think it's more useful for it to search spellings, since we have a way for doing phonological searches separately, so could we either switch back to the other column order, or switch it so that the search box always searches the spelling column?

**Comment by kchall** [comment]
we switched it back to being spelling first

**Comment by jsmackie** [comment]
This appears to work inconsistently with example and IPHOD because the "spelling" column is underlyingly a factor-type column, instead of a spelling-type. This causes it to get sorted after tier-type columns. I'll fix this and put new copies on dropbox. For newly created corpora, this won't be a problem.
