### ISSUE TITLE
ProD environments cause PCT to crash

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#743]
Running ProD on the example corpus with pair [m], [n]. If no environment is selected at all, analysis runs normally and a frequency-only result is calculated as expected. If a non-exhaustive list of environments is given (e.g., only #__ ), and "Enforce exhaustivity" is selected, PCT correctly identifies that the list is not exhaustive and shows missing words. But if an exhaustive list is given (e.g., #__ , e__, o__), PCT just crashes entirely. No error message is printed to the console.

**Comment by kchall** [comment]
Note: the algorithm is working okay in the current release, 1.4.1 -- just not in the current master branch. @stannam is it possible that something you did in adding an environment filter to MI affected the behaviour for ProD?

**Comment by stannam** [comment]
I found out what the problem is. It is not from the environment filter, as the algorithm itself runs without any issue. 
The culprit seems to be the new result window. I'll fix it shortly.

**Comment by kchall** [comment]
Excellent, thanks, @stannam !

**Comment by stannam** [comment]
The problem was mainly a GUI issue and not related to the environment filter. It occurred _after_ finishing the calculation and when reporting the results.  

The issue was from that a value for 'Algorithm name,' the new column in the result window, was only provided when no environment is selected, but the result window still requires one anyway. When the user specifies environments, 'Algorithm name' does not feed to the result window, and the result window needs a value for 'Algorithm name', thus crash. 

Specifically, I didn't notice that the kwargs (i.e., result values from a calculation) for the result window are assigned separately between when an environment is specified or not. So I simply made PCT generate the 'Algorithm name' column only when no environment is specified. I should have added the same line of code for the case where an environment is specified. 

I have double-checked it in other functions and there should not be the same problem.
