### ISSUE TITLE
PCT crashes when downloading feature files

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#755]
When trying to download a feature file (at least with buckeye2hayes and ipa2hayes -- I haven't tested others), PCT crashes entirely. This is using a Mac (10.13.6) on the master branch of PCT. No error message is given.

**Comment by stannam** [comment]
I couldn't replicate this issue but I guess it might be similar to this stackoverflow thread:
https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org

If so, the problem is that python cannot use the certificate verification required for connecting to an HTTP**S** link. Since we use https links of dropbox (e.g., http**s**://www.dropbox.com/s/wglm3fuhxivnc8g/xyz.corpus?dl=1) I think it is very likely. 

There are two solutions. 
1. Temporarily disable certificate verification on an individual connection
```
import ssl

context = ssl._create_unverified_context()
urllib.urlopen("https://no-valid-cert", context=context)

```
2. Let the user to run on terminal
```
/Applications/Python\ [Python version number]/Install\ Certificates.command
```

**Comment by stannam** [comment]
I could replicate this issue by intentionally disconnecting from the internet before doing downloads.....
