### ISSUE TITLE
[BUG] Interlinear Corpus Won't Load; PCT Crashes

### ISSUE THREAD

**Issue by blru2021** [PhonologicalCorpusTools/CorpusTools#768]
**Describe the bug**
I have created a tab delimited interlinear corpus but when I try to load it PCT shows an error. 

**Sample corpus file**
[Sample corpus fort Github.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/6768552/Sample.corpus.fort.Github.txt)

**To Reproduce**
Maybe the problem is with the corpus so below are the steps on how I created it on PCT
1. Go to 'File>Load Corpora>Create corpus from file'
2. Click on 'Choose file' and load file (transcription system already in use from existing ones)
3. Click on 'Interlinear Corpus'
4. I see 'Number of lines per gloss (auto-detected) = 4 (but my corpus has two lines - i.e., columns - only, spelling and transcription)
3. Go to 'Parsing Preview' and edit Line names and properties
4. Line 1: name 'Spelling'; Annotation type (Orthography default); I select 'Associate this with the lexical item'
5. Line 2: name 'Transcription'; Annotation type (Transcription default) select 'Allow this property to vary within lexical items'
6. Line 3: name 'Line 3'; Annotation type (Notes - ignored)
7. Line 4: name 'Line 4'; Annotation type (Notes - ignored)
8. I see the following error:
---
Traceback (most recent call last):
  File "corpustools\gui\iogui.py", line 91, in run
  File "corpustools\corpus\io\text_ilg.py", line 246, in load_discourse_ilg
  File "corpustools\corpus\io\text_ilg.py", line 192, in ilg_to_data
AttributeError: 'str' object has no attribute 'begin'
---

**Expected behavior**
I would like the corpus to load so I can perform various analyses.

**Screenshots**
<img width="886" alt="Screenshot PCT problem 2021-07-06 105634" src="https://user-images.githubusercontent.com/87008344/124572638-14ed3180-de49-11eb-8f13-199e8a2c9b05.png">

**Operating system and PCT version**
 - Windows 10 Enterprise, version 20H2
 - PCT version: [e.g. v1.4.1]

**Additional context**
Update: I created a new corpus in Notepad++ with the canonical and alternative transcriptions in two different lines. The corpus is created (and the number of lines correctly identified) but when I try to load the corpus PCT crashes.

**Comment by stannam** [comment]
Hi @blru2021 , thanks for pointing this out.

It seems to me that the txt file you linked is in the column-delimited format. 

The file can be loaded on my machine as a column-delimited corpus, using the default settings. Could you try to load it as column-delimited? 

![image](https://user-images.githubusercontent.com/43150234/125221731-8c71f500-e27d-11eb-96c2-9790d2a13a3e.png)
(... and many other words)

FYI, [this](https://www.dropbox.com/s/d0znc5it9p3wu0h/pron_var_from_spelling.txt?dl=1) is a sample interlinear (space delimited) file. I think you refer to it if you want to have your file loaded as an interlinear corpus. 

I hope this helps. Please let me know if anything is not clear!

**Comment by blru2021** [comment]
Hi,

 

Thanks so much for your response! 

 

I was able indeed to open the file as a column-delimited corpus but I am not sure whether I can do the same analyses as I would be able to do with an interlinear corpus. For example, when I try to measure functional load, I can only see the transcription tier with the corpus loaded as is. Also, when I open the file on my computer, I see that frequencies are only indicated as 1 for the first instance and then the rest is indicated as 0. I am not sure how to interpret this. Might it be that I should use spelling instead of default transcription? (see attachment) 

In addition, when I upload a new corpus where the tiers are transcription (default) and transcription (alternative), I get the error message that the string has no stress pattern – I was not aware that if you upload alternative transcription stress has to be marked.

 

At any rate, I had already a file with different lines of spelling/transcription (i.e., not column-delimited) which did not work as well, – but  now I think the problem is that the lines were too long. It seems that if I reduce the length of the lines it might work to upload the corpus as a interlinear text. If I have more problems I hope can reach out again.

 

Thanks again and all the best,

Borana

**Comment by blru2021** [comment]
Update:

 

Here’s a sample of the final interlinear corpus file I am using. The entire file has 4830 lines. The corpus is successfully created on PLC with the first line titled Transcription and Annotation Type = transcription and the second line titled Alternative and Annotation Type = transcription alternative. When I try to load it, it crashes. I tried also with the attached sample, which is smaller in size, it still crashes. 

 

Does the attached file open on your machine?

 

 

Thanks again for your help,

Borana

**Comment by stannam** [comment]
Hi Borana @blru2021 ,

Yes, PCT does crash, and that is because it cannot handle the interlinear format without an orthography line. That is actually a problem and it needs to be fixed.

In the meantime, I created a corpus from the file by adding a dummy orthography line. The dummy line is the same as the 'transcription.'

Can you download [this file](https://www.dropbox.com/s/xhmyqj9afjh45sh/new_interlinear.corpus?dl=1) and test loading it? You first need to save the file in “C:\Users\[USER NAME]\Documents\PCT\CorpusTools\CORPUS”, and then it will appear as one of the 'available corpora' in Load corpora (Ctrl + O on the main screen of PCT). 

Please see [here](https://corpustools.readthedocs.io/en/master/downloading_and_installing.html#local-storage) regarding the path for CORPUS.

**Comment by blru2021** [comment]
Hi,

 

Sorry to bother again – I would really appreciate your help.

 

So I created an interlinear corpus (sample attached: three rows, spelling, transcription, variants) and it loads on PCT finally, which is great. But now when I try to do any analysis taking into account the variants, (please see screenshot for the specific settings) I get the following error:

 

Traceback (most recent call last):

File "corpustools\gui\flgui.py", line 42, in run

File "corpustools\funcload\functional_load.py", line 155, in deltah_fl_vectorized

AttributeError: 'Word' object has no attribute 'Transcription'

 

I thought it might be because on some lines the spelling row is below the transcription and variants row, so I am combing through the lines but it still does not work with the corrected sample corpus that I am attaching here.

 

I hope there’s something to be done.

 

Thanks,

Borana

**Comment by stannam** [comment]
Hi Borana @blru2021 ,

Unfortunately, I cannot see the attachment nor screenshots. You might need to post them on the original issue page on Github https://github.com/PhonologicalCorpusTools/CorpusTools/issues/768 .

From the error message, though, it seems like you tried to calculate functional load by entropy change. Since I don't replicate this issue without the corpus file, I want to see if the error only happens with the function you were trying. Does this issue persist when you do other analyses, such as 'predictability of distribution' or 'mutual information'?

**Comment by blru2021** [comment]
Hi,

 

Yes, indeed, the issue is only if I calculate functional load by entropy change, and it persists when I do ‘predictability of distribution’. However, it did work when I tried to measure functional load by minimal pairs (trouble is I know there are very few minimal pairs in my corpus so that is a bit useless).

 

I will upload the files on the github page.

 

Thank you so much for all your help!

Borana

**Comment by blru2021** [comment]
Files
Screenshot of PCT analysis I want to make

<img width="689" alt="screenshot pct functional load" src="https://user-images.githubusercontent.com/87008344/126947358-26c82c78-d0cd-4bae-b501-deeb15607597.png">

Sample corpus
[test interlinear.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/6876259/test.interlinear.txt)

**Comment by stannam** [comment]
Hi @blru2021 ,

Thanks for the sample file and screenshot. I could replicate the error, and the problem comes from the option for pronunciation variants. PCT didn't crash when I selected 'Pronunciation variants' option 'use canonical forms only' and 'use most frequent forms only.' 

The error is unintended, and it actually is a bug that needs to be fixed. I'm sorry but there is no solution at this moment. I think I need to sit down and look into the codes to figure out how to solve it. I'll get back to you as soon as possible. Sorry about that!

**Comment by blru2021** [comment]
Hi,

 

Thanks very much for your help and prompt responses. At the risk of being a bit impolite, do you think the bug could be fixed by the end of august? I have a presentation then and I wanted to include the PCT analyses results as well.

 

Best,

Borana

**Comment by stannam** [comment]
Hi Borana @blru2021 

Sorry I have kept you waiting. I have just fixed the issue. If you can run PCT from the codes please update to the latest version. (I've also created a temporary Windows executable [here](https://www.dropbox.com/s/ndktw5fqcudyo41/PCT.exe?dl=1) if you prefer this way.)

Please let me know if PCT still crashes with this update.

//

I have created a tiny corpus for sanity check. If you want to follow the explanation below, please add [this corpus file](https://www.dropbox.com/s/rnqytm7yib679l1/tiny_sample.corpus?dl=1) to the local storage.


The 'tiny_sample' corpus has only two word types: 'taka' and 'gaka'. 

There are 5 tokens for 'taka': 3 'taka', 2 'taga'
![image](https://user-images.githubusercontent.com/43150234/127945129-3fbf8a5d-d78e-4dff-a2a7-da239c669f2f.png)


There are 2 tokens for 'gaka': 1 'gaka', 1 'gaga'
![image](https://user-images.githubusercontent.com/43150234/127945142-7c036f32-fe96-4bfe-b5fd-5dd621cc3d00.png)


Let's say we want to calculate functional load of [t, g] by entropy change.

![image](https://user-images.githubusercontent.com/43150234/127945446-e7740ac5-ba23-43ea-bff6-8329eb97db60.png)

Since we know that we are going to set the variant option to 'weight each word type...' I hand calculated the 'temporary' corpus that is used in the functional load algorithm. (The column Weighted variants in the above picture)
3 'taka' tokens out of 5 variants of the 'taka' type..... 3/5 = 0.6
2 'taga' tokens out of 5 variants of the 'taka' type..... 2/5 = 0.4
and so on.

On the right hand side, an imaginary corpus where t and g are merged. (marked as X)


If the pronunciation variant option is set to canonical, and calculating by the token frequency...
![image](https://user-images.githubusercontent.com/43150234/127945854-a42aaeac-89f7-4d38-a90e-584de803bbf9.png)

We can hand calculate the functional load as 0.863120569.

And this is what PCT calculates as well.
![image](https://user-images.githubusercontent.com/43150234/127945951-00e5b1bb-7021-4a08-bded-dd2ff90ba827.png)


If the pronunciation variant option is set to 'weight each word type...' and calculating by the token frequency...
![image](https://user-images.githubusercontent.com/43150234/127946022-c3c620b8-1012-48e9-a2b8-7be58d812e77.png)

The hand calculation will be 0.9927
![image](https://user-images.githubusercontent.com/43150234/127946057-9b63a2bb-af9f-4df3-8ca6-547b33b58381.png)

to which PCT agrees..
![image](https://user-images.githubusercontent.com/43150234/127946160-302b46d7-58d7-424d-b875-9eb93ffdf6fd.png)

**Comment by blru2021** [comment]
Hi,

 

It is indeed fixed and PCT does not crash when I perform analyses.

 

Thank you!

Borana
