### ISSUE TITLE
[BUG] PCT crashing - macOS BigSur M1

### ISSUE THREAD

**Issue by mkachlicka** [PhonologicalCorpusTools/CorpusTools#789]
After downloading and installing, the PCT crashes when calling the acoustic similarity feature.

I checked for dependencies (Python 3.8 & all required packages installed) and tried installing both versions of dmg and fallback via terminal.

**Screenshots**
I attached the copied text of the error message

**Operating system and PCT version**
 - OS: MacOS Big Sur Version 11.6
 - PCT version: v1.4.1
 
[error from pct.pdf](https://github.com/PhonologicalCorpusTools/CorpusTools/files/7586810/error.from.pct.pdf)

**Comment by kchall** [comment]
Thanks for the report! Can I check: were you specifically trying to use the 'amplitude envelopes' representation instead of MFCCs? I can get the crashing behaviour with amplitude envelopes, but MFCCs are currently working for me. 

We'll look into it, but I should say up front that we're not actively maintaining the acoustic similarity tool. We generally point people now to the phonetic counterpart of PCT: Montreal Corpus Tools and their various repositories (including Speech Corpus Tools): https://github.com/orgs/MontrealCorpusTools/repositories.

**Comment by stannam** [comment]
Hi, we've looked into this, and the error seems to be from a problem we already fixed (related to issue #718).

We confirmed that acoustic similarity works on later versions, so could you please download the pre-released executable from https://github.com/PhonologicalCorpusTools/CorpusTools/releases/tag/v1.5.0 , or try to sync to the latest codes?
