### ISSUE TITLE
Questions about release notes

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#796]
- I have removed the release notes from from the website (http://phonologicalcorpustools.github.io/CorpusTools/) and replaced with links to ReadtheDocs / GitHub. 

- I made .txt file versions of the notes for 1.2.0-1.5.0. These have been added to https://github.com/PhonologicalCorpusTools/CorpusTools/tree/master/docs/source/release and listed on https://github.com/PhonologicalCorpusTools/CorpusTools/blob/master/docs/source/release.rst. But they are not showing up online on ReadtheDocs: https://corpustools.readthedocs.io/en/latest/release.html. What am I doing wrong? 

- Should I also update the specific notes on each release (https://github.com/PhonologicalCorpusTools/CorpusTools/releases) to match the .txt files? Or is it odd to change those at this point?

**Comment by stannam** [comment]
* I changed the extension from .txt to .rst and they are now showing up on Readthedocs. https://corpustools.readthedocs.io/en/latest/release.html

* I don't think we need to match the past release info on github to the release notes, because we already provide much information on the release page. However, we could use the release notes when we release 1.5.0 soon!

**Comment by kchall** [comment]
Ah! Of course...that was silly. Thank you for your fresh eyes! :)
