### ISSUE TITLE
Phonological search: Add option to list up target segments separately in summary results

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#801]
![image](https://user-images.githubusercontent.com/43150234/161172532-09546a92-854f-4c83-bdcf-74d85b63e284.png)

Currently, the phonological search result window repeats the user input. But it will be better off by adding an option to view the summary results in the old way, i.e., each row by segments.

**Need to implement/solve/decide**
 - [x] when the search has no hits, PCT should not crash. 
   - I remember this error existed in the old way of result summary. (can't find among the closed issues, though.)
 - [x] what should PCT do when the user redoes searches but changes the summarize_by_segments settings? 
   - Currently, it follows the most recent value e.g., if True then False, the summary window repeats the user input.
   - → Decided to keep it this way
 - [x] make sure the numbers add up, i.e., the results are true to the data.
 - [x] Option wording:  “List target segments **and environments** separately in summary results.”
 
 **Test the function** 
   - [x] with very complicated searches (especially, multiple segments in the environments)
     - For this, I searched for {i OR a} proceded by {ʃ OR g} and PCT returned correct results. Specifically, the parameters I used were (env: {ʃ, g}_; target: i, a), on the example corpus. Therefore, PCT should find four sequences of ʃi, gi, ʃa, ga. Four words in the corpus, ɡaɡa, ʃaʃi, ʃi, ʃisota contain one of those sequences.
   - [x] with the syllabified example corpus
   - [x] input by both 'add segments' and 'add features'
   - [x] duplicating a search (see #765, and #762)

**Update documentation**
 - [x] Make sure the documentation is updated to make the functionality clear. In particular, make it clear that (under the current functionality), if results are listed separately, every combination is considered separately, but different parts of the same environment are still combined (e.g. {#, i} {s, ʃ} {i, a} results in four environments for each of the two target segments): #_i, #_a, i_i, and i_a.

**Comment by stannam** [comment]
Question:
When calculating type frequency of [ʃ], should 'shushoma' be counted twice?
![image](https://user-images.githubusercontent.com/43150234/161653207-73762210-2890-421f-9a9f-dd794f36e693.png)

**Comment by kchall** [comment]
1. If you ask PCT to list the target results separately, it does so initially in the summary results, but when you then go to the individual results and back to the summary results, the summary results revert to the combined targets. The behaviour should be static.

2. When I try to replicate the example search about type frequency you showed earlier, @stannam, I get a different result (and more expected!). E.g., if I search for [ʃ] in the example corpus, then the summary results show a type frequency of 6, not 9, and that matches the six individual words found, regardless of the number of target segments each word contains:

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/7317450/162049709-9a2a1626-3654-4196-b556-c4f25c3057f5.png">

So, that’s alarming that our machines are giving us different results! But you also seem to have deleted the comment that showed that example, so maybe you discovered something in the meantime?

3. Furthermore, the way that type frequency is being treated seems to be *different* depending on whether the targets are listed separately or not! If the search is for [s, ʃ] in the example corpus, and the default / combined view is used, then I get the expected result that matches what I got above, i.e., each word counts once, regardless of the number of target segments it contains, for a total type frequency of 8, in 8 unique words: 

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/7317450/162049812-e85204e9-8874-406c-987b-6868b24b3471.png">

BUT, if I do the same search but ask for the results to be separated out by targets, I get 5 for [s] and 9 for [ʃ]. While it’s fine in this case for words that have both [s] AND [ʃ] to get ‘double counted’ (one in each result row), that *should* give the result of 4 for [s] and 6 for [ʃ]. But instead, it’s doing the double-counting targets by word that you had originally reported, @stannam, so that e.g. [sasi] counts as two ‘types’ for [s] instead of 1.

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/7317450/162049890-06902709-6723-4619-bd46-30f6fcb07c5e.png">

Note that if I do now go back to the summary results, it reverts *completely* to the not-separated-by-target option (as mentioned in point (1) above), i.e., that entails re-combining the type frequencies and not double-counting within words, i.e., I get 8 again and not 14 (which would be 9+5):

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/7317450/162049985-8fbb6336-f5c4-4619-996c-7f36afb8c636.png">

*************
I think the desired behaviour should be:
1. results display should be static, so if a user has asked for results to be split out by target, they should always get that, even if they toggle back and forth between ‘summary’ and ‘individual’ results;
2. a word should count only once toward type frequency (and its token frequency similarly only used once), regardless of the number of target segments it contains. 


[As a side note, I’ll just comment to remind myself: I did check to see whether the behaviour was the same if the targets were specified with features instead of segments, i.e., [+continuant, -syllabic], and the results are identical to those described above.]

**Comment by stannam** [comment]
1. The settings for the result display should be static
 - That is strange. I could not replicate this issue on the virtual MacOS environment (macOS Monterey). 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/43150234/164117553-901abbe1-a71c-4e3c-8fbf-9f0a2d470e42.gif)

2. A word should count only once toward type frequency
 - I'm working on this issue... To make sure that I'm on the same page, searching for [s, ʃ] in the example corpus should yield something like the following.

![image](https://user-images.githubusercontent.com/43150234/164119726-0173f7d4-21b5-4498-a5b5-9789bedad036.png)

because in the individual results: 
![image](https://user-images.githubusercontent.com/43150234/164119768-2c255a56-f5c8-425e-8ff2-64cb47874bb0.png)

**Comment by stannam** [comment]
I think I fixed the type frequency issue. 

I tested on the following two types of use case scenarios. It worked as expected.

**1. Use case 1: Searching for [s, ʃ] (see above)** 
 - desired results: 

| symbol | type F | token F |
| -------- | ------- | -------- |
|    s        |    4       |     275  |
|    ʃ         |    6       |     179  |

.
.

**2. Use case 2: Searching for [s, ʃ], but the environment is specified as [_a, _i]**
 - i.e., 
![image](https://user-images.githubusercontent.com/43150234/164133054-35043864-acd8-4ce4-bdf2-9c5845e3845b.png)

 - in this case, 'sasi' should be counted twice, once for [sa] and another for [si].
 - desired results: 
![image](https://user-images.githubusercontent.com/43150234/164134384-eb6d603f-6d3d-41d3-b8dc-14d383f40d5e.png)


 - because in the individual results:
![image](https://user-images.githubusercontent.com/43150234/164134404-72920689-b5a1-49b6-8be4-7103a760e54e.png)

@kchall Can you update to the latest codes and test on your machine whether the summary setting is static and the results are correct?

**Comment by stannam** [comment]
cf. #356

**Comment by kchall** [comment]
Thanks, Stanley! This mostly seems to be fixed, but there are two separate follow-ups. I'll list them in two separate comments for clarity.

**Comment by kchall** [comment]
First, the more serious bug:

Leaving aside doing ‘combined’ searches for the moment, I tried just doing two individual searches, one for [s] and one for [ʃ]. 

Weirdly, if I do these searches literally one at a time (a search for [s] and then, separately, a search for [ʃ]), everything is fine, even if I add the results to the current results table. 

Results if I do the searches separately:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/7317450/166305658-9c20ea4c-c4dd-40fd-b9e1-7c58074594af.png">

BUT if I define two *separate* environments at the same time (which should give the same result), the results for the first environment ([s] in this case) are correct, but the ones for the second ([ʃ]) are not — it seems to have somehow added in one of the [s] words into the total counts for [ʃ] (specifically, the numbers make sense if it’s counting [sasi] as an [ʃ] word!). (And similarly, it gets [ʃ] correct but [s] wrong if the order is switched.)

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/7317450/166305713-10284440-f5a6-42ca-97c0-80547f65ed78.png">

Results for the ‘combined’ search of two separate environments:
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/7317450/166305758-9d1727e7-ac49-4cca-8d1c-8746ec6e94c8.png">

**Comment by kchall** [comment]
The second issue is more about clarity of what we mean when we someone selects "List target segments separately in summary results."

Currently, what is actually happening (and thanks for pointing this out through your second test case above!) is that both the targets AND the environments are getting split out. For example, if the basic search definition is to search for [s, ʃ] before [i, a], and the results are separated, PCT currently separates out both the targets and the environments, yielding four results rows (for [si], [sa], [ʃi], and [ʃa]) (and this seems to be working correctly). 

But with the way the option is worded, I would have expected it to separate out the targets and NOT the environments, so that you get just two results rows (for [s] before [i, a] and [ʃ] before [i, a]). 

I think we should proceed as follows:

1. Change the text of the current option button to say “List target segments and environments separately in summary results.”

2. Check with the person who requested this functionality to see whether she specifically wanted one or both of these options. If she just wants the one we're currently doing, fine, we'll leave it as is. 

3. If she wanted both or she only cared about the one we're NOT currently doing, let's ADD a new option button that does say “List target segments separately in summary results" and indeed has that functionality.

4. Either way, make sure the documentation is updated to make the functionality clear. In particular, make it clear that (under the current functionality), if results are listed separately, every combination is considered separately, but different parts of the same environment are still combined (e.g. {#, i} {s, ʃ} {i, a} results in four environments for each of the two target segments): #_i, #_a, i_i, and i_a.

**Comment by stannam** [comment]
Thanks, Kathleen for looking into this.

**re: One search with separate environments gives wrong numbers**

I think I fixed this error now. I confirmed that the numbers are correct. It turned out that a conditional I added to the summary function (f359d5e4169d1ae8b465ba006f0308fa67b6393f) overapplies to some words. I simply made changes to bypass this conditional if the user selected the 'split' option. 

Previously when I was working on the summary results, I added a feature that makes 'zero frequency rows' if some conditions are met. For example, if we search for a readily illegal sequence like [gst] on example _without_ the 'split' option, PCT still returns a row, rather than an empty window. It depends on whether the main phonological search function returned None ('not found'). The logic is: if there is a value, then a search must have happened with that parameters, but None means nothing found --- so add a row but give zero values for token and type frequencies.

However, for some reason, the phonological search function wrongly adds redundant None values if more than one environment is used. These redundant None values are wrongly translated by the summary side as a need for adding zero frequencies, messing the frequency counts for the second environment. 

For now, I do not understand why this is happening in the main function. Someone should investigate this eventually, but I think it does not need to be a top priority since the final results are not affected either on the individual or summary window. 


**re: Splitting the environment segments**

I emailed the user to ask if the other option would be needed. Once I hear back, I will make changes accordingly.

**Comment by kchall** [comment]
Thanks, @stannam! But, weirdly, this doesn't seem to have fixed the error on my Mac -- I synced to the latest version and see your commit in the history, but when I do the two searches together, I still get the wrong result for the second one:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/7317450/167033318-2a32fcd3-ad49-4555-8e7c-593377f7b27b.png">

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/7317450/167033343-eda00245-42cc-4f22-b0bd-e8df2ea686ae.png">

(Interestingly, this *does* work correctly if I check the option for separating out the targets in the results!)

**Comment by kchall** [comment]
I have updated the https://github.com/PhonologicalCorpusTools/CorpusTools/blob/master/docs/source/phonological_search.rst documentation, including updating the existing search interface images, to include the "List separately" option. So far, though, it doesn't seem to be actually syncing with https://corpustools.readthedocs.io/en/latest/phonological_search.html -- the build is failing. But I'm not savvy enough to understand what the actual issue is.

**Comment by stannam** [comment]
Note to myself:
for separate envs see #771 and commit b812d576f753fdf7d6bd676286d4bcad90406115

**Comment by stannam** [comment]
@kchall could you synced to the latest codes and see if problems are all fixed?

**re: documentation build failing (https://github.com/PhonologicalCorpusTools/CorpusTools/issues/801#issuecomment-1119112323)**
Readthedocs automatically imports the latest version of Sphinx, which is a package for rendering rst files to html. But that latest version seems buggy, making the builds fail (sometimes, the newest might not be the best one). So I forced the version that worked for PCT previously. 

**re: fixing the PS summary function**
I think I fixed the summary function for good. I tested various use case scenarios, including the negative search and syllable search (a lengthy comment is [here](https://github.com/PhonologicalCorpusTools/CorpusTools/issues/801#issuecomment-1120382765) ). Can you check if everything is correct on your end?

**Comment by kchall** [comment]
I can confirm that all of the above seems to be working correctly now on my end as well! With the (exception?) that in #3, "[sɑ] [ʃɑ] Syllable search," I *am* able to do a negative search as long as I have the environments combined into a single set and don't try to separate out the results. My syllabified example corpus doesn't have [ga.ga] in it, but the results for the search do seem to be correct for my corpus, i.e., with type frequency of 11 and token of 362 for "words that do not contain either [sɑ] or [ʃɑ]." So, I think it is all working correctly...yay!
